#!/bin/bash

RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m\n')" END="$(printf '\033[0m\e[0m')"

ip=$(cat $1 | grep for | head -n1 | awk '{print $NF}')
ports=$(cat $1 | grep -oP '^\d+' | paste -sd ",")
echo -e "\n[${ORANGE}>${END}] ${ORANGE}Puertos campturados del archivo: ${BLUE}$1${END}"
echo -e "\t[${GREEN}+${END}] ${GREEN}Direccion IP:${END} $ip"
echo -e "\t[${GREEN}+${END}] ${GREEN}Puertos:${END} $ports"
echo $ports | xclip -sel clip
echo -e "[${ORANGE}>${END}] ${ORANGE}Los puertos han sido copiados en la Clip Board${END}"
